### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by 0risc** [jwodder/demagnetize-rs#118]
v0.2.0 doesn't build due to the following error
```
error: lint `pointer_structural_match` has been removed: converted into hard error, see RFC #3535 <https://rust-lang.github.io/rfcs/3535-constants-in-patterns.html> for more information
  |
  = note: requested on the command line with `-D pointer_structural_match`
  = note: requested on the command line with `-D renamed-and-removed-lints`
```
This issue was [fixed back in May](https://github.com/jwodder/demagnetize-rs/commit/14c86ccc571216200c803aa4d2ec333bbdc40e00) but a new version was not tagged

**Comment by jwodder** [comment]
Thanks for letting me know!  Version 0.2.1 is out now with the latest code.
