### ISSUE TITLE
support lib crate

### ISSUE THREAD

**Issue by vuhe** [jwodder/demagnetize-rs#39]
I want to use this crate as a lib. Do you have any plans to support a lib crate?

**Comment by jwodder** [comment]
No.

**Comment by izissise** [comment]
I have the same usage, @vuhe could you find an alternative?

**Comment by vuhe** [comment]
> I have the same usage, @vuhe could you find an alternative?

I have found a simple way to solve this problem:

1. You can use this [crate](https://crates.io/crates/hightorrent) get magnet hash.
2. Replace hash string to uppercase (only supported v1 sha1 hash).
3. Request `https://itorrents.org/torrent/{torrent_hash}.torrent`, `{torrent_hash}` is sha1 uppercase hash string.

This can solve most problems, but it does not support v2 torrent.

**Comment by izissise** [comment]
Thanks you :)
